function recommendation = mm_choose_chart(task)
%MM_CHOOSE_CHART Route an analytical task to a defensible chart family.

key = lower(strtrim(string(task)));
switch key
    case {"trend", "time", "time_series"}
        values = {"line_with_markers", "ordered x with meaningful spacing", ...
            "smoothed curve that hides sparse observations"};
    case {"category", "category_compare", "comparison"}
        values = {"sorted_horizontal_bar_or_dot", "common quantitative scale", ...
            "3-D or unsorted rainbow bars"};
    case {"distribution", "uncertainty"}
        values = {"ecdf_or_histogram_plus_box_points", ...
            "sample size, groups, and bins disclosed", "mean-only bar chart"};
    case {"relationship", "correlation"}
        values = {"scatter_with_justified_fit", "paired observations", ...
            "lines connecting unordered observations"};
    case {"model_performance", "diagnostics"}
        values = {"residual_calibration_error_panels", ...
            "out-of-sample or validation predictions", "training fit only"};
    case {"optimization", "tradeoff", "pareto"}
        values = {"pareto_decision_profile_constraint_slack", ...
            "feasibility and objectives disclosed", "isolated objective value"};
    case {"sensitivity", "robustness"}
        values = {"tornado_response_curve_or_two_factor_heatmap", ...
            "perturbation basis disclosed", "arbitrary +/-10 percent"};
    case {"spatial", "map"}
        values = {"map_with_scale_legend_projection", ...
            "valid coordinates and geographic context", "rainbow map without units"};
    case {"matrix", "heatmap"}
        values = {"sequential_or_diverging_heatmap", ...
            "ordered scale and meaningful midpoint", "categorical rainbow scale"};
    case {"exact", "exact_lookup", "table"}
        values = {"table", "exact values are the task", "decorative dense chart"};
    otherwise
        error('mathmodel:UnknownChartTask', ...
            '未知分析任务 "%s"；请先定义读者要比较的关系。', key);
end

recommendation = struct( ...
    'task', char(key), ...
    'recommended', values{1}, ...
    'required_condition', values{2}, ...
    'reject_by_default', values{3});
end
